theme: minima

title: Tristan & Grace's Wedding

description: Wedding details, RSVP, travel tips, and contacts.

minima:
  skin: auto

header_pages:
  - reception_idaho_falls.md
  - sealing_dc_temple.md
  - reception_dc.md
  - travel_and_lodging.md
  - rsvp.md
  - registry.md
  - faq.md
  - contact.md

permalink: pretty

markdown: kramdown

kramdown:
  input: GFM

show_excerpts: false
show_downloads: false

plugins:
  - jekyll-feed

exclude:
  - README.md
  - .gitignore
