theme: minima

minima:
  skin: auto

header_pages: []

permalink: pretty

markdown: kramdown

kramdown:
  input: GFM

show_excerpts: false
show_downloads: false

plugins:
  - jekyll-feed

exclude:
  - README.md
  - .gitignore
